github: ['schorschii']
liberapay: schorschii
custom: ['https://georg-sieber.de/?page=app-fsclock', 'https://play.google.com/store/apps/details?id=systems.sieber.fsclock', 'https://www.amazon.com/gp/product/B09BK3HQJ9']
